server:
  port: 8088

sa:
  # 登录账号
  name: admin
  # 登录密码
  pwd: 123456
  # 是否随机生成账号密码（为true则name与pwd失效）
  auto: false
  # 是否开启全局认证（关闭后将不再强行拦截）
  auth: true
  # 登录页标题
  title: 快速登录
  # 是否显示底部版权信息
  copr: true
  # 指定排除路径
  exclude: /test
